sudo: required
services:
  - docker

before_install:
  - docker network create bnet
  - docker pull synadia/bridge-ibmmq:latest
  - docker pull synadia/bridge-activemq:latest
  - docker pull synadia/bridge-nats-server:latest
  - docker pull synadia/bridge-travis-build:latest


script:
  - docker run --net bnet --name nats-server -d synadia/bridge-nats-server:latest
  - docker run --net bnet --name active-mq -d synadia/bridge-activemq:latest
  - docker run --net bnet --name ibm-mq -d synadia/bridge-ibmmq:latest
  - docker run --net bnet --name bridge -v $(pwd):/usr/app synadia/bridge-travis-build:latest

after_script:
  - docker rm -f $(docker ps -aq)
  - docker network remove bnet