version: '3'
services:
  nats-server:
    build:
      context: ../
      dockerfile: cicd/Dockerfile
    ports:
      - "4222:4222"
      - "8222:8222"
  ibm-mq:
    build:
      context: ../
      dockerfile: cicd/Dockerfile_ibmmq.dev
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
  active-mq:
    image: 'vromero/activemq-artemis'
    environment:
      - ARTEMIS_USERNAME=cloudurable
      - ARTEMIS_PASSWORD=cloudurable
    ports:
      - "8161:8161"
      - "61616:61616"
  bridge-admin:
    container_name: bridge-admin
    image: 'cloudurable/nats-bridge-admin-nginx'
    working_dir: /usr/app/admin
    #command: ["sleep","infinity"]
    #command: bash -c "./gradlew bootRun"
    ports:
      - "443:443"
