# Test that uses docker image of IBM MQ that sets every setting different than the default.
# This is to test passing IBM MQ params in the Bridge admin.
version: '3'
services:
  nats-server:
    build:
      context: ../bridge-nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
  ibm-mq:
    build:
      context: ../bridge-ibmmq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
    ports:
      - "1414:1414"
      - "8443:9443"
  active-mq:
    build:
      context: ../bridge-activemq
    environment:
        - ARTEMIS_USERNAME=cloudurable
        - ARTEMIS_PASSWORD=cloudurable
    ports:
      - "8161:8161"
      - "61616:61616"
  bridge-admin_1:
    container_name: bridge-admin_1
    image: 'gilmarmacieljr/bridge-admin'
    environment:
      - TARGET=host.docker.internal
    working_dir: /usr/app/bridge
    command: ["sleep","infinity"]
    ports:
      - "8070:8080"
  bridge-admin_2:
    container_name: bridge-admin_2
    image: 'gilmarmacieljr/bridge-admin'
    environment:
      - TARGET=host.docker.internal
    working_dir: /usr/app/bridge
    command: ["sleep","infinity"]
    ports:
      - "8090:8080"
  bridge-admin_3:
    container_name: bridge-admin_3
    image: 'gilmarmacieljr/bridge-admin'
    environment:
      - TARGET=host.docker.internal
    working_dir: /usr/app/bridge
    command: ["sleep","infinity"]
    ports:
      - "8060:8080"
